::Left4Grief.Settings <-
{
	// [1/0] 1 = Admins can abort any vote by voting NO
	admin_can_abort_vote = 1
	
	// [1/0] Enable/Disable the anti disconnect grief code
	// 1 = When a player throws a molotov/pipe bomb or shoots a grenade launcher and quickly disconnects, such damaging entities (flames, nades, projectiles etc..) are automatically removed from the map
	// in order to prevent the friendly fire damage (which cannot be blocked as usual if the attacker is no longer in the game)
	// NOTE: Indirectly ignited entities will still be there causing damage. Sadly, it's not possible to know who ignited them
	anti_disconnect_grief = 1
	
	// [1/0] Enable/Disable the anti-rush check for the admins
	antirush_admins = 0
	
	// Max distance (in game units) of the rusher from the other teammates before getting punished
	antirush_distance = 2000
	
	// [1/0] 1 = Enable/Disable the "go back" punishment (the rusher will be teleported back to the position of the last teammate)
	antirush_punish_goback = 1
	
	// [1/0] 1 = Enable/Disable the "slow down" punishment (the rusher will be slowed down)
	antirush_punish_slowdown = 0
	
	// [1/0] 1 = Enable/Disable the "vomit" punishment (the rusher will get a boomer vomit effect)
	antirush_punish_vomit = 0
	
	// [1/0] Enable/Disable the anti-rush check for the non admins
	antirush_users = 1
	
	// [1/0] Enable/Disable the onscreen notifications (to admins only) of the players FAULTs
	// NOTE: FAULTs are generated by the game itself, the addon only shows them to the admins/public when they are generated (so don't ask me to explain what they mean or to modify them)
	fault_admin_alert = 1
	
	// [1/0] Enable/Disable the onscreen notifications (to everyone) of the players FAULTs
	// NOTE: FAULTs are generated by the game itself, the addon only shows them to the admins/public when they are generated (so don't ask me to explain what they mean or to modify them)
	fault_public_alert = 0
	
	// [1/0] Enable/Disable the friendly fire for non admins and bots
	// NOTE: Friendly fire must also be enabled via game CVARs in order to enable it
	friendly_fire = 1
	
	// [1/0] Enable/Disable the friendly fire for admins only
	// NOTE: Friendly fire must also be enabled via game CVARs in order to enable it
	friendly_fire_admins = 1

	// Minimum log level for the addon's log lines into the console
	// 0 = No log
	// 1 = Only [ERROR] messages are logged
	// 2 = [ERROR] and [WARNING]
	// 3 = [ERROR], [WARNING] and [INFO]
	// 4 = [ERROR], [WARNING], [INFO] and [DEBUG]
	loglevel = 3
	
	// [1/0] Enable/Disable the friendly fire (and reverse FF) invulnerability when a teammate is pinned by a special infected (charger, hunter, jockey and smoker)
	pin_invulnerability = 1
	
	// Additional invulnerability time (in seconds) after the pinned survivor gets freed
	pin_invulnerability_time = 1.0

	// [1/0] Enable/Disable the auto incap for the player who tries to heal a teammate on a ladder
	// When disabled, the healing is still blocked to prevent the fall, but without incapping the healer
	punish_heal_onladder = 0
	
	// [1/0] Enable/Disable the auto kick for the player who tries to vote kick the admins
	revenge_kick = 0
	
	// [1/0] Enable/Disable the reverse friendly fire for the admins
	ricochet_admins = 0
	
	// Reverse friendly fire damage caused by explosions is multiplied by this factor
	ricochet_blast_damagefactor = 0.1
	
	// [1/0] Enable/Disable the reverse friendly fire for the bots
	ricochet_bots = 0
	
	// Reverse friendly fire damage caused by fire is multiplied by this factor
	ricochet_burn_damagefactor = 0.1
	
	// Reverse friendly fire damage (not caused by explosions/fire) is multiplied by this factor
	ricochet_damagefactor = 1
	
	// [1/0] Enable/Disable the reverse friendly fire for the non admins
	ricochet_users = 1
	
	// [1/0] 0 = Non admins cannot cast votes
	user_can_cast_vote = 1
	
	// [1/0] Enable/Disable the "All Talk" vote type
	vote_change_all_talk = 1
	
	// [1/0] Enable/Disable the "Change Chapter" vote type
	vote_change_chapter = 1
	
	// [1/0] Enable/Disable the "Change Difficulty" vote type
	vote_change_difficulty = 1
	
	// [1/0] Enable/Disable the "Change Mission" vote type
	vote_change_mission = 1
	
	// [1/0] Enable/Disable the "Kick" vote type
	vote_kick = 1
	
	// [1/0] Enable/Disable the "Campaign Restart" vote type
	vote_restart_game = 1
	
	// [1/0] Enable/Disable the "Return To Lobby" vote type
	vote_return_to_lobby = 1
}
